- type: entity
  parent: RMCBaseMeleeWeapon
  id: MCWeaponGun
  abstract: true
  components:
  - type: UsableWhileDevoured
    canUnequip: true
  - type: GunIFF
    enabled: false
  - type: RMCWeaponDamageFalloff
  - type: Clothing
    quickEquip: false
  - type: UseDelay
    delay: 0
  - type: WieldDelay
  - type: AltFireMelee
  - type: MeleeWeapon
    attackRate: 1
    damage:
      types:
        Blunt: 5
    soundHit:
      collection: GenericHit
  - type: EmitSoundOnPickup
    sound:
      collection: RMCEquipGun
  - type: EmitSoundOnLand
    sound:
      collection: RMCRustleGun
  - type: Gun
    meleeCooldownOnShoot: false
    resetOnHandSelected: false
    burstCooldown: 0
  - type: RMCWeaponAccuracy
  - type: Appearance
  - type: WieldedCrosshair
    rsi:
      sprite: _RMC14/Interface/MousePointer/pistol_mouse.rsi
      state: all
  - type: InteractionActivateOnClick

- type: entity
  id: MCAttachableHolder
  abstract: true
  components:
  - type: AttachableHolder
  - type: ItemSizeChange
  - type: ActivatableUI
    verbText: rmc-verb-strip-attachables
    verbOnly: true
    key:
      enum.AttachmentUI.StripKey
  - type: UserInterface
    interfaces:
      enum.AttachmentUI.StripKey:
        type: AttachmentStripBui
      enum.AttachmentUI.ChooseSlotKey:
        type: AttachmentChooseSlotBui

- type: Tag
  id: MCMagazineRifle

- type: Tag
  id: MCMagazineShotgun

- type: Tag
  id: MCMagazineHandful
