- type: entity
  parent: BaseChemistryEmptyBottle
  id: MCBottleEmpty
  components:
  - type: Item
    size: Small
    sprite: _MC/Objects/Chemistry/bottles.rsi
  - type: Sprite
    sprite: _MC/Objects/Chemistry/bottles.rsi
    layers:
    - state: bottle-1
    - state: bottle-1-1
      map: ["enum.SolutionContainerLayers.Fill"]
      visible: false
    - state: lid_bottle-1
      map: ["enum.OpenableVisuals.Layer"]
      visible: false
  - type: SolutionContainerManager
    solutions:
      drink:
        maxVol: 60
  - type: SolutionContainerVisuals
    maxFillLevels: 6
    fillBaseName: bottle-1-
  - type: Openable
    opened: true
    closeable: true
    examineText: rmc-bottle-closed
    openVerbText: rmc-bottle-remove-lid
    closeVerbText: rmc-bottle-put-lid
    sound: null
  - type: GenericVisualizer
    visuals:
      enum.OpenableVisuals.Opened:
        enum.OpenableVisuals.Layer:
          True: {visible: false}
          False: {visible: true}
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: GlassBreak
          params:
            volume: -4
      - !type:SpillBehavior { }
      - !type:SpawnEntitiesBehavior
        spawn:
          CMShardGlass:
            min: 0
            max: 1
        transferForensics: true
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: InteractedBlacklist
    blacklist:
      components:
      - Xeno
  - type: Clothing
    quickEquip: false
    slots:
    - suitstorage
  - type: SolutionTransfer
    transferAmount: 60
    maxTransferAmount: 60
    canChangeTransferAmount: true
    transferAmounts:
    - 5
    - 10
    - 15
    - 25
    - 30
    - 40
    - 60
  - type: DamageOnLand
    damage: {}
  - type: DamageOtherOnHit
    damage: {}
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 2
    damage: {}
  - type: RMCSmartFridgeInsertable
    category: Bottle

- type: entity
  parent: MCBottleEmpty
  id: MCBottleFilled
  abstract: true
  suffix: Filled
  components:
  - type: Tag
    tags:
    - MCBottle
  - type: CMRefillableSolution
    solution: drink

- type: Tag
  id: MCBottle
