- type: entity
  id: MCXenoStructure
  abstract: true
  components:
  - type: GuideHelp
    guides:
    - RMCGuideHiveStructures
  - type: Transform
    anchored: true
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49"
        layer:
        - BulletImpassable
        density: 200
  - type: InteractionOutline
  - type: Clickable
  - type: Damageable
    damageContainer: StructuralXeno
    damageModifierSet: Resin
  - type: RMCNightVisionVisible
    priority: -1
    transparency: 0.2
  - type: XenoConstruct
  - type: XenoAnnounceStructureDestruction
  - type: RequireProjectileTarget
  - type: Flammable
    fireSpread: false
    maximumFireStacks: 0.5
    damage:
      types:
        Heat: 3.8
  - type: Corrodible
    isCorrodible: false
